"""Compare fresh Attachment4 inference with the submitted final CSV core outputs."""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

TOL = 1e-6
MODALITIES = ("text", "audio", "vision")


def read_csv(path: Path):
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def seq_string(sample: dict, target: str, modality: str) -> str:
    items = sample["targets"][target]["modalities"][modality]["top_positions"]
    return ";".join(str(int(x["official_seq_index"])) for x in items)


def close(a, b):
    return abs(float(a) - float(b)) <= TOL


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--generated", type=Path, required=True)
    ap.add_argument("--submitted", type=Path, required=True)
    args = ap.parse_args()

    submitted = {r["sample_id"]: r for r in read_csv(args.submitted)}
    if set(submitted) != {f"{i:02d}" for i in range(1, 21)}:
        raise ValueError("submitted CSV must contain exactly samples 01-20")

    errors = []
    checked_numeric = 0
    checked_seq = 0

    for sid in (f"{i:02d}" for i in range(1, 21)):
        sample = json.loads((args.generated / "samples" / f"sample_{sid}.json").read_text(encoding="utf-8"))
        row = submitted[sid]
        pred = sample["prediction"]

        if pred["class_name"] != row["predicted_class"]:
            errors.append([sid, "predicted_class", pred["class_name"], row["predicted_class"]])

        for label, field in (("Negative", "p_negative"), ("Neutral", "p_neutral"), ("Positive", "p_positive")):
            checked_numeric += 1
            if not close(pred["probabilities"][label], row[field]):
                errors.append([sid, field, pred["probabilities"][label], row[field]])

        checked_numeric += 1
        if not close(pred["intensity"], row["predicted_intensity"]):
            errors.append([sid, "predicted_intensity", pred["intensity"], row["predicted_intensity"]])

        for target, prefix in (("classification", "cls"), ("regression", "reg")):
            phi = sample["targets"][target]["shapley"]["phi"]
            for modality in MODALITIES:
                checked_numeric += 1
                field = f"phi_{prefix}_{modality}"
                if not close(phi[modality], row[field]):
                    errors.append([sid, field, phi[modality], row[field]])

                checked_seq += 1
                seq_field = f"top_seq_{prefix}_{modality}"
                observed = seq_string(sample, target, modality)
                if observed != row[seq_field]:
                    errors.append([sid, seq_field, observed, row[seq_field]])

    payload = {
        "status": "PASS" if not errors else "FAIL",
        "sample_count": 20,
        "numeric_values_checked": checked_numeric,
        "top_sequence_lists_checked": checked_seq,
        "tolerance_abs": TOL,
        "mismatch_count": len(errors),
        "mismatches_first20": errors[:20],
        "note": "Verified raw-media evidence fields are frozen submission annotations and are not regenerated by this core model check."
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    if errors:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
